# ----------------------------------------
# Basic site settings
# ----------------------------------------
remote_theme: raviriley/agency-jekyll-theme

url       : "https://www.dialecticalpraxis.com"
baseurl   : ""                 # leave empty for root‐domain site

title       : "dialectical praxis"
#email       : ""
description : "Professional website for Derron Borders."
author      : "Derron Borders"

logo:
  path  : "/assets/img/dplogo.png"
  height: 60

locale: "en-US"


# ----------------------------------------
# Collections
# ----------------------------------------
collections:
  portfolio:
    output: true




# ----------------------------------------
# Markdown processor
# ----------------------------------------
markdown: kramdown


# ----------------------------------------
# Plugins (GitHub Pages–allowed only)
# ----------------------------------------
plugins:
  - jekyll-remote-theme
